### ISSUE TITLE
流程列表接口与webhook推送数据格式不一致

### ISSUE THREAD

**Issue by xiaohaha444** [GreenNerd/SLP-ChangeLog#2]
上饶交警 field_value  违法行为,车辆类型,违法地址 字段的 value 
在列表API中返回的格式为 
[{"id":1212,"gid":"gid:\/\/skylark\/Option\/1212","value":"蓝色车牌（蓝底白字）"}]

在webhook中推送的格式为
[{"gid":"gid:\/\/skylark\/Option\/1212"},{"id":"1212"},{"value":"蓝色车牌（蓝底白字）"}]

能否统一为列表API的数据格式

**Comment by hw676018683** [comment]
我感觉是一样的，我去测试确认下

**Comment by hw676018683** [comment]
我测试出来，是一致的，你在测试下呢

**Comment by xiaohaha444** [comment]
{"action":"proposed","assignment":{"id":"3276","created_at":"2018-07-10 12:32:17 +0800","updated_at":"2018-07-10 12:32:17 +0800","vertex_id":"945","status":"processing","response":{"id":"6868","created_at":"2018-07-10 11:46:42 +0800","updated_at":"2018-07-10 12:32:17 +0800","cached_values":{"1848":{"value":["2018-07-10"],"text_value":["2018-07-10"],"exported_value":["2018-07-10"]},"1849":{"value":["8899"],"text_value":["8899"],"exported_value":["8899"]},"1850":{"value":[{"gid":"gid:\/\/skylark\/Option\/1212"},{"id":"1212"},{"value":"\u84dd\u8272\u8f66\u724c\uff08\u84dd\u5e95\u767d\u5b57\uff09"}],"text_value":["\u84dd\u8272\u8f66\u724c\uff08\u84dd\u5e95\u767d\u5b57\uff09"],"exported_value":["\u84dd\u8272\u8f66\u724c\uff08\u84dd\u5e95\u767d\u5b57\uff09"]},"1851":{"value":[{"gid":"gid:\/\/skylark\/Option\/1219"},{"id":"1219"},{"value":"\u73ed\u7ebf\u7ecf\u8425\u8005\u8fdd\u89c4\u7ad9\u5916\u4e0a\u5ba2\u3001\u6cbf\u9014\u63fd\u5ba2\u3001\u5f3a\u884c\u62c9\u5ba2\u3001\u7529\u5ba2\u3001\u5012\u5ba2"}],"text_value":["\u73ed\u7ebf\u7ecf\u8425\u8005\u8fdd\u89c4\u7ad9\u5916\u4e0a\u5ba2\u3001\u6cbf\u9014\u63fd\u5ba2\u3001\u5f3a\u884c\u62c9\u5ba2\u3001\u7529\u5ba2\u3001\u5012\u5ba2"],"exported_value":["\u73ed\u7ebf\u7ecf\u8425\u8005\u8fdd\u89c4\u7ad9\u5916\u4e0a\u5ba2\u3001\u6cbf\u9014\u63fd\u5ba2\u3001\u5f3a\u884c\u62c9\u5ba2\u3001\u7529\u5ba2\u3001\u5012\u5ba2"]},"1852":{"value":[{"value":"\u56db\u5ddd\u7701\u6210\u90fd\u5e02\u6b66\u4faf\u533a\u6842\u6eaa\u8857\u9053\u8700\u90fd\u4e2d\u5fc3(\u5317\u533a)\u8700\u90fd\u4e2d\u5fc3"},{"longitude":"104.0642"},{"latitude":"30.55464"}],"text_value":["\u56db\u5ddd\u7701\u6210\u90fd\u5e02\u6b66\u4faf\u533a\u6842\u6eaa\u8857\u9053\u8700\u90fd\u4e2d\u5fc3(\u5317\u533a)\u8700\u90fd\u4e2d\u5fc3"],"exported_value":["\u56db\u5ddd\u7701\u6210\u90fd\u5e02\u6b66\u4faf\u533a\u6842\u6eaa\u8857\u9053\u8700\u90fd\u4e2d\u5fc3(\u5317\u533a)\u8700\u90fd\u4e2d\u5fc3"]},"1853":{"value":["\u5929\u5e9c\u65b0\u533a"],"text_value":["\u5929\u5e9c\u65b0\u533a"],"exported_value":["\u5929\u5e9c\u65b0\u533a"]},"1854":{"value":[{"gid":"gid:\/\/skylark\/Attachment\/2228"},{"id":"2228"},{"value":"90000002_thumb.jpg"}],"text_value":["90000002_thumb.jpg"],"exported_value":["90000002_thumb.jpg\uff08https:\/\/beta.skylarkly.com\/attachments\/2228\/download\uff09"]},"1856":{"value":["\u6d4b\u8bd5\u8f6c\u4ea4"],"text_value":["\u6d4b\u8bd5\u8f6c\u4ea4"],"exported_value":["\u6d4b\u8bd5\u8f6c\u4ea4"]},"1857":{"value":["18681250580"],"text_value":["18681250580"],"exported_value":["18681250580"]},"1858":{"value":["555555555555555555"],"text_value":["555555555555555555"],"exported_value":["555555555555555555"]},"1859":{"value":["luhanv"],"text_value":["luhanv"],"exported_value":["luhanv"]},"1860":{"value":["\u54c8\u54c8"],"text_value":["\u54c8\u54c8"],"exported_value":["\u54c8\u54c8"]},"1861":{"value":["\u8fdd\u6cd5"],"text_value":["\u8fdd\u6cd5"],"exported_value":["\u8fdd\u6cd5"]}}},"journey":{"id":"742","created_at":"2018-07-10 12:32:17 +0800","updated_at":"2018-07-10 12:32:17 +0800","sn":"16420180710114642000006","status":"processing","current_vertex_id":"947","reviewer_vertex_ids":["945"]},"user":{"id":"256","created_at":"2018-06-29 12:34:54 +0800","updated_at":"2018-06-29 12:34:54 +0800","name":"\u4e3e\u4e2a\u8354\u679d","identifier":"oXDm5sxqlHiGERUVnPVqcwqiQBbE","headimgurl":"http:\/\/thirdwx.qlogo.cn\/mmopen\/vi_32\/8SpBA9A4Q4lOPYodFYPiak77oHsHhheW6FSiaOpTr9Cdnz6JxaXdmQ8VXjZrZUCxskYwbcMPBHYpFTWvGItm8W8w"}},"flow":{"id":"164","created_at":"2018-07-09 14:58:08 +0800","updated_at":"2018-07-09 15:02:27 +0800","title":"\u89c6\u9891\u4e3e\u62a5"}} 

这是webhook推送过来 我写在文件内的数据  格式化一下就能看出来

**Comment by hw676018683** [comment]
感觉造成这个差异的原因是双方框架对`Content-Type`为`application/x-www-form-urlencoded`的数据，处理方式不一样
如果我把默认方式改成`application/json`，对城建那边有影响吗

**Comment by xiaohaha444** [comment]
应该没有影响 你可以改成json  我这边在用城建代码测试一下

**Comment by hw676018683** [comment]
改了，beta已部署
